/*
Chameleon - Skin Changer by piggd
Email: dayzpiggd@gmail.com
Website: http://dayzpiggd.enjin.com
Dontaions Accepted via paypal to danpigg@yahoo.com

Based on Skin_Trader by boyd
http://epochmod.com/forum/index.php?/topic/12378-release-skin-trader-06-buy-any-arma-skin/
*/
disableSerialization;
private["_worldname","_modVariant","_modVariantSelcted","_overpoch"];
if(isnil "CSC_WORLD") then {
	CSC_WORLD = "unknown";
};
_worldname=toLower format ["%1",worldName];
// *************************************************************************************************************************
// Uncomment the line below to activate Overpoch Skins or add this variable to your init.sqf file. Above your chameleon_init.sql call.
// CSC_WORLD = "overpoch"; 
// *************************************************************************************************************************
_modVariant = CSC_WORLD;
_overpoch=false;
if (_modVariant == "overpoch") then  {_overpoch=true;};
if (_overpoch) then {
	_modVariantSelcted = "overpoch";
} else {
	_modVariantSelcted = "epoch";
};
diag_log format ["Chameleon: Has detected %1 %2 Map Loaded.",_modVariantSelcted,_worldname];

//CSCFreeSkins = true;
CSCFreeSkins = false;
CSCFreePrice = ["ItemGoldBar",0];

// Regular Skin Price
CSCGlobalPrice = ["ItemGoldBar",4];  // Do not set to 0 unless you have CSCFreeSkins = true;
//CSCGlobalPrice = ["ItemGoldBar10oz",2];  // Do not set to 0 unless you have CSCFreeSkins = true;
//CSCGlobalPrice = ["ItemBriefcase100oz",2];  // Do not set to 0 unless you have CSCFreeSkins = true;

// Special Skin Prices
CSCSpecialPrice1 = ["ItemGoldBar",2]; // Do not set to 0
CSCSpecialPrice2 = ["ItemGoldBar10oz",1]; // Do not set to 0
CSCSpecialPrice3 = ["ItemGoldBar",6]; // Do not set to 0
CSCSpecialPrice4 = ["ItemGoldBar",7]; // Do not set to 0

CSCFreeSkinList = [
	"Survivor2_DZ",
	"SurvivorW2_DZ"
];

//Default Epoch Skins
CSCSpecialSkinList1 = AllPlayers;
//CSCSpecialSkinList1 = [
//	"Survivor2_DZ",
//	"SurvivorW2_DZ"
//];
	
CSCSpecialSkinList2 = [
"gsc_cloth_loner_head",
"gsc_eco_stalker_head_camo1",
"gsc_eco_stalker_head_duty",
"gsc_eco_stalker_head_fred",
"gsc_eco_stalker_head_neutral",
"gsc_eco_stalker_mask_camo",
"gsc_eco_stalker_mask_duty",
"gsc_eco_stalker_mask_fred",
"gsc_eco_stalker_mask_neutral",
"gsc_military_head_grey",
"gsc_military_head_grey_AT",
"gsc_military_head_greySNP",
"gsc_military_head_wdl",
"gsc_military_head_wdl_AT",
"gsc_military_head_wdlSNP",
"gsc_military_helmet_grey",
"gsc_military_helmet_grey_AT",
"gsc_military_helmet_greySNP",
"gsc_military_helmet_wdl",
"gsc_military_helmet_wdl_AT",
"gsc_military_helmet_wdlSNP",
"gsc_scientist1",
"gsc_scientist1_head",
"gsc_scientist2",
"gsc_scientist2_head"
];
CSCSpecialSkinList3 = [
//	"Survivor2_DZ",
//	"SurvivorW2_DZ"
];
CSCSpecialSkinList4 = [
//	"Survivor2_DZ",
//	"SurvivorW2_DZ"
];

CSCMenClothing = [
"Survivor2_DZ",
"BAF_ASoldier_DDPM",
"BAF_ASoldier_MTP",
"BAF_ASoldier_W",
"BAF_crewman_DDPM",
"BAF_crewman_MTP",
"BAF_creWman_W",
"BAF_Pilot_DDPM",
"BAF_Pilot_MTP",
"BAF_Pilot_W",
"BAF_Soldier_AA_DDPM",
"BAF_Soldier_AA_MTP",
"BAF_Soldier_AA_W",
"BAF_Soldier_AAA_DDPM",
"BAF_Soldier_AAA_MTP",
"BAF_Soldier_AAA_W",
"BAF_Soldier_AAR_DDPM",
"BAF_Soldier_AAR_MTP",
"BAF_Soldier_AAR_W",
"BAF_Soldier_AAT_DDPM",
"BAF_Soldier_AAT_MTP",
"BAF_Soldier_AAT_W",
"BAF_Soldier_AHAT_DDPM",
"BAF_Soldier_AHAT_MTP",
"BAF_Soldier_AHAT_W",
"BAF_Soldier_AMG_DDPM",
"BAF_Soldier_AMG_MTP",
"BAF_Soldier_AMG_W",
"BAF_Soldier_AR_DDPM",
"BAF_Soldier_AR_MTP",
"BAF_Soldier_AR_W",
"BAF_Soldier_AT_DDPM",
"BAF_Soldier_AT_MTP",
"BAF_Soldier_AT_W",
"BAF_Soldier_DDPM",
"BAF_Soldier_FAC_DDPM",
"BAF_Soldier_FAC_MTP",
"BAF_Soldier_FAC_W",
"BAF_Soldier_GL_DDPM",
"BAF_Soldier_GL_MTP",
"BAF_Soldier_GL_W",
"BAF_Soldier_HAT_DDPM",
"BAF_Soldier_HAT_MTP",
"BAF_Soldier_HAT_W",
"BAF_Soldier_L_DDPM",
"BAF_Soldier_L_MTP",
"BAF_Soldier_L_W",
"BAF_Soldier_Marksman_DDPM",
"BAF_Soldier_Marksman_MTP",
"BAF_Soldier_Marksman_W",
"BAF_Soldier_MG_DDPM",
"BAF_Soldier_MG_MTP",
"BAF_Soldier_MG_W",
"BAF_Soldier_MTP",
"BAF_Soldier_N_DDPM",
"BAF_Soldier_N_MTP",
"BAF_Soldier_N_W",
"BAF_Soldier_Officer_DDPM",
"BAF_Soldier_Officer_MTP",
"BAF_Soldier_Officer_W",
"BAF_Soldier_scout_DDPM",
"BAF_Soldier_scout_MTP",
"BAF_Soldier_scout_W",
"BAF_Soldier_SL_DDPM",
"BAF_Soldier_SL_MTP",
"BAF_Soldier_SL_W",
"BAF_Soldier_Sniper_MTP",
"BAF_Soldier_Sniper_W",
"BAF_Soldier_SniperH_MTP",
"BAF_Soldier_SniperH_W",
"BAF_Soldier_SniperN_MTP",
"BAF_Soldier_SniperN_W",
"BAF_Soldier_spotter_MTP",
"BAF_Soldier_spotter_W",
"BAF_Soldier_spotterN_MTP",
"BAF_Soldier_spotterN_W",
"BAF_Soldier_TL_DDPM",
"BAF_Soldier_TL_MTP",
"BAF_Soldier_TL_W",
"BAF_Soldier_W",
"Bandit1_DZ",
"Camo1_DZ",
"CDF_Soldier",
"CDF_Soldier_AR",
"CDF_Soldier_Crew",
"CDF_Soldier_Engineer",
"CDF_Soldier_GL",
"CDF_Soldier_Marksman",
"CDF_Soldier_Medic",
"CDF_Soldier_MG",
"CDF_Soldier_Militia",
"CDF_Soldier_Officer",
"CDF_Soldier_Pilot",
"CDF_Soldier_RPG",
"CDF_Soldier_Sniper",
"CDF_Soldier_Spotter",
"CDF_Soldier_Strela",
"CDF_Soldier_TL",
"CZ_Soldier_AMG_DES_EP1",
"CZ_Soldier_AT_DES_EP1",
"CZ_Soldier_B_DES_EP1",
"CZ_Soldier_DES_EP1",
"CZ_Soldier_MG_DES_EP1",
"CZ_Soldier_Pilot_EP1",
"CZ_Soldier_SL_DES_EP1",
"CZ_Soldier_Sniper_EP1",
"CZ_Special_Forces_DES_EP1",
"CZ_Special_Forces_GL_DES_EP1",
"CZ_Special_Forces_MG_DES_EP1",
"CZ_Special_Forces_Scout_DES_EP1",
"CZ_Special_Forces_TL_DES_EP1",
"Dixon_PMC",
"Drake",
"Drake_Light",
"FR_AC",
"FR_AR",
"FR_Assault_GL",
"FR_Assault_R",
"FR_Commander",
"FR_Cooper",
"FR_Corpsman",
"FR_GL",
"FR_Light",
"FR_Marksman",
"FR_Miles",
"FR_OHara",
"FR_R",
"FR_Rodriguez",
"FR_Sapper",
"FR_Sykes",
"FR_TL",
"GER_Soldier_EP1",
"GER_Soldier_MG_EP1",
"GER_Soldier_Scout_EP1",
"GER_Soldier_TL_EP1",
"Graves",
"Graves_Light",
"GUE_Commander",
"GUE_Soldier_1",
"GUE_Soldier_2",
"GUE_Soldier_3",
"GUE_Soldier_AA",
"GUE_Soldier_AR",
"GUE_Soldier_AT",
"GUE_Soldier_CO",
"GUE_Soldier_Crew",
"GUE_Soldier_GL",
"GUE_Soldier_Medic",
"GUE_Soldier_MG",
"GUE_Soldier_Pilot",
"GUE_Soldier_Sab",
"GUE_Soldier_Scout",
"GUE_Soldier_Sniper",
"Ins_Soldier_1",
"Ins_Soldier_2",
"Ins_Soldier_AA",
"Ins_Soldier_AR",
"Ins_Soldier_AT",
"Ins_Soldier_CO",
"Ins_Soldier_Crew",
"Ins_Soldier_GL",
"Ins_Soldier_MG",
"Ins_Soldier_Sab",
"Ins_Soldier_Sapper",
"Ins_Soldier_Sniper",
"MVD_Soldier",
"MVD_Soldier_AT",
"MVD_Soldier_GL",
"MVD_Soldier_Marksman",
"MVD_Soldier_MG",
"MVD_Soldier_Sniper",
"MVD_Soldier_TL",
"Pierce",
"Pierce_Light",
"Reynolds_PMC",
"Rocket_DZ",
"RU_Soldier",
"RU_Soldier_AA",
"RU_Soldier_AR",
"RU_Soldier_AT",
"RU_Soldier_Crew",
"RU_Soldier_GL",
"RU_Soldier_HAT",
"RU_Soldier_LAT",
"RU_Soldier_Marksman",
"RU_Soldier_MG",
"RU_Soldier_Officer",
"RU_Soldier_Pilot",
"RU_Soldier_SL",
"RU_Soldier_Sniper",
"RU_Soldier_SniperH",
"RU_Soldier_Spotter",
"RU_Soldier_TL",
"RU_Soldier2",
"RUS_Commander",
"RUS_Soldier_GL",
"RUS_Soldier_Marksman",
"RUS_Soldier_TL",
"RUS_Soldier1",
"RUS_Soldier2",
"RUS_Soldier3",
"Ry_PMC",
"Sniper1_DZ",
"Soldier_AA_PMC",
"Soldier_AT_PMC",
"Soldier_Bodyguard_AA12_PMC",
"Soldier_Bodyguard_M4_PMC",
"Soldier_GL_M16A2_PMC",
"Soldier_GL_PMC",
"Soldier_M4A3_PMC",
"Soldier_MG_PKM_PMC",
"Soldier_MG_PMC",
"Soldier_Pilot_PMC",
"Soldier_PMC",
"Soldier_Sniper_KSVK_PMC",
"Soldier_Sniper_PMC",
"Soldier_TL_PMC",
"Soldier1_DZ",
"Survivor3_DZ",
"Tanny_PMC",
"TK_Aziz_EP1",
"TK_Commander_EP1",
"TK_GUE_Soldier_2_EP1",
"TK_GUE_Soldier_3_EP1",
"TK_GUE_Soldier_4_EP1",
"TK_GUE_Soldier_5_EP1",
"TK_GUE_Soldier_AA_EP1",
"TK_GUE_Soldier_AAT_EP1",
"TK_GUE_Soldier_AR_EP1",
"TK_GUE_Soldier_AT_EP1",
"TK_GUE_Soldier_EP1",
"TK_GUE_Soldier_HAT_EP1",
"TK_GUE_Soldier_MG_EP1",
"TK_GUE_Soldier_Sniper_EP1",
"TK_GUE_Soldier_TL_EP1",
"TK_GUE_Warlord_EP1",
"TK_INS_Soldier_2_EP1",
"TK_INS_Soldier_3_EP1",
"TK_INS_Soldier_4_EP1",
"TK_INS_Soldier_AA_EP1",
"TK_INS_Soldier_AAT_EP1",
"TK_INS_Soldier_AR_EP1",
"TK_INS_Soldier_AT_EP1",
"TK_INS_Soldier_EP1",
"TK_INS_Soldier_MG_EP1",
"TK_INS_Soldier_Sniper_EP1",
"TK_INS_Soldier_TL_EP1",
"TK_INS_Warlord_EP1",
"TK_Soldier_AA_EP1",
"TK_Soldier_AAT_EP1",
"TK_Soldier_AMG_EP1",
"TK_Soldier_AR_EP1",
"TK_Soldier_AT_EP1",
"TK_Soldier_B_EP1",
"TK_Soldier_Crew_EP1",
"TK_Soldier_Engineer_EP1",
"TK_Soldier_EP1",
"TK_Soldier_GL_EP1",
"TK_Soldier_HAT_EP1",
"TK_Soldier_LAT_EP1",
"TK_Soldier_MG_EP1",
"TK_Soldier_Night_1_EP1",
"TK_Soldier_Night_2_EP1",
"TK_Soldier_Officer_EP1",
"TK_Soldier_Pilot_EP1",
"TK_Soldier_SL_EP1",
"TK_Soldier_Sniper_EP1",
"TK_Soldier_Sniper_Night_EP1",
"TK_Soldier_SniperH_EP1",
"TK_Soldier_Spotter_EP1",
"TK_Soldier_TWS_EP1",
"TK_Special_Forces_EP1",
"TK_Special_Forces_MG_EP1",
"TK_Special_Forces_TL_EP1",
"UN_CDF_Soldier_AAT_EP1",
"UN_CDF_Soldier_AMG_EP1",
"UN_CDF_Soldier_AT_EP1",
"UN_CDF_Soldier_B_EP1",
"UN_CDF_Soldier_Crew_EP1",
"UN_CDF_Soldier_EP1",
"UN_CDF_Soldier_Guard_EP1",
"UN_CDF_Soldier_Light_EP1",
"UN_CDF_Soldier_MG_EP1",
"UN_CDF_Soldier_Officer_EP1",
"UN_CDF_Soldier_Pilot_EP1",
"UN_CDF_Soldier_SL_EP1",
"US_Delta_Force_Air_Controller_EP1",
"US_Delta_Force_AR_EP1",
"US_Delta_Force_Assault_EP1",
"US_Delta_Force_EP1",
"US_Delta_Force_M14_EP1",
"US_Delta_Force_Marksman_EP1",
"US_Delta_Force_MG_EP1",
"US_Delta_Force_Night_EP1",
"US_Delta_Force_SD_EP1",
"US_Delta_Force_TL_EP1",
"US_Delta_Force_Undercover_Takistani06_EP1",
"US_Soldier_AA_EP1",
"US_Soldier_AAR_EP1",
"US_Soldier_AAT_EP1",
"US_Soldier_AHAT_EP1",
"US_Soldier_AMG_EP1",
"US_Soldier_AR_EP1",
"US_Soldier_AT_EP1",
"US_Soldier_B_EP1",
"US_Soldier_Engineer_EP1",
"US_Soldier_EP1",
"US_Soldier_GL_EP1",
"US_Soldier_HAT_EP1",
"US_Soldier_LAT_EP1",
"US_Soldier_Marksman_EP1",
"US_Soldier_MG_EP1",
"US_Soldier_Pilot_EP1",
"US_Soldier_SL_EP1",
"US_Soldier_Sniper_EP1",
"US_Soldier_Sniper_NV_EP1",
"US_Soldier_SniperH_EP1",
"US_Soldier_Spotter_EP1",
"US_Soldier_TL_EP1",
"USMC_LHD_Crew_Blue",
"USMC_LHD_Crew_Brown",
"USMC_LHD_Crew_Green",
"USMC_LHD_Crew_Purple",
"USMC_LHD_Crew_Red",
"USMC_LHD_Crew_White",
"USMC_LHD_Crew_Yellow",
"USMC_Soldier",
"USMC_Soldier_AA",
"USMC_Soldier_AR",
"USMC_Soldier_AT",
"USMC_Soldier_GL",
"USMC_Soldier_HAT",
"USMC_Soldier_LAT",
"USMC_Soldier_MG",
"USMC_Soldier_Pilot",
"USMC_Soldier_SL",
"USMC_Soldier_TL",
"USMC_SoldierM_Marksman",
"USMC_SoldierS",
"USMC_SoldierS_Engineer",
"USMC_SoldierS_Sniper",
"USMC_SoldierS_SniperH",
"USMC_SoldierS_Spotter"
];

CSCWomanClothing = [
	"SurvivorW2_DZ",
	"SurvivorW3_DZ",
	"SurvivorWcombat_DZ",
	"SurvivorWdesert_DZ",
	"SurvivorWurban_DZ",
	"SurvivorWpink_DZ",
	"BanditW1_DZ",
	"BanditW2_DZ"
];

if (_modVariant == "Overpoch") then {
CSCMenClothing = CSCMenClothing +[
"arma1_us_soldier_sabass",
"arma1_us_soldier_sabmark",
"arma1_us_soldier_sabot",
"DANEG",
"DANEG1",
"DANEG10",
"DANEG2",
"DANEG3",
"DANEG4",
"DANEG6",
"DANEG7",
"DANEG8",
"Desert_SOF_AC",
"Desert_SOF_AT",
"Desert_SOF_DA1",
"Desert_SOF_DA1a",
"Desert_SOF_DA1b",
"Desert_SOF_DA2",
"Desert_SOF_GL",
"Desert_SOF_Marksman",
"Desert_SOF_MG",
"Desert_SOF_Sabot",
"Desert_SOF_Shotgun",
"Desert_SOF_TL",
"frb_gl",
"frb_gl_mask",
"frb_mark",
"frb_mark_mask",
"frb_mg",
"frb_mg_mask",
"frb_stealth_mark",
"frb_stealth_rifleman",
"frb_stealth_sabot",
"frb_stealth_tl",
"frb_tl",
"frb_tl_mask",
"G_Mercenary_Default20b",
"gsc_cloth_loner_head",
"gsc_eco_stalker_head_camo1",
"gsc_eco_stalker_head_duty",
"gsc_eco_stalker_head_fred",
"gsc_eco_stalker_head_neutral",
"gsc_eco_stalker_mask_camo",
"gsc_eco_stalker_mask_duty",
"gsc_eco_stalker_mask_fred",
"gsc_eco_stalker_mask_neutral",
"gsc_military_head_grey",
"gsc_military_head_grey_AT",
"gsc_military_head_greySNP",
"gsc_military_head_wdl",
"gsc_military_head_wdl_AT",
"gsc_military_head_wdlSNP",
"gsc_military_helmet_grey",
"gsc_military_helmet_grey_AT",
"gsc_military_helmet_greySNP",
"gsc_military_helmet_wdl",
"gsc_military_helmet_wdl_AT",
"gsc_military_helmet_wdlSNP",
"gsc_scientist1",
"gsc_scientist1_head",
"gsc_scientist2",
"gsc_scientist2_head",
"Mercenary_Default20b",
"Mercenary_Default20c",
"Mercenary_Default20d",
"Navy_SEAL_AC",
"Navy_SEAL_ACa",
"Navy_SEAL_ACb",
"Navy_SEAL_AT",
"Navy_SEAL_diver",
"Navy_SEAL_diver_land",
"Navy_SEAL_diver_medic",
"Navy_SEAL_GL",
"Navy_SEAL_Marksman",
"Navy_SEAL_MG",
"Navy_SEAL_Sabot",
"Navy_SEAL_SD",
"Navy_SEAL_Shotgun",
"Navy_SEAL_TL",
"SBH_Alpha_Soldier1",
"SBH_Alpha_Soldier10",
"SBH_Alpha_Soldier11",
"SBH_Alpha_Soldier12",
"SBH_Alpha_Soldier2",
"SBH_Alpha_Soldier3",
"SBH_Alpha_Soldier4",
"SBH_Alpha_Soldier5",
"SBH_Alpha_Soldier6",
"SBH_Alpha_Soldier7",
"SBH_Alpha_Soldier8",
"SBH_Alpha_Soldier9",
"SFSG_des_ar",
"SFSG_des_demo",
"SFSG_des_jtac",
"SFSG_des_mrk",
"SFSG_des_op",
"SFSG_des_tl",
"SFSG_mtp_ar",
"SFSG_mtp_demo",
"SFSG_mtp_jtac",
"SFSG_mtp_mrk",
"SFSG_mtp_op",
"SFSG_mtp_tl",
"SFSG_mtpw_ar",
"SFSG_mtpw_demo",
"SFSG_mtpw_jtac",
"SFSG_mtpw_med",
"SFSG_mtpw_mrk",
"SFSG_mtpw_op",
"SFSG_mtpw_tl",
"SFSG_wdl_ar",
"SFSG_wdl_demo",
"SFSG_wdl_jtac",
"SFSG_wdl_mrk",
"SFSG_wdl_op",
"SFSG_wdl_tl",
"UKSF_des_ar",
"UKSF_des_ar_l",
"UKSF_des_demo",
"UKSF_des_demo_l",
"UKSF_des_jtac",
"UKSF_des_jtac_l",
"UKSF_des_mrk",
"UKSF_des_mrk_l",
"UKSF_des_op",
"UKSF_des_op_l",
"UKSF_des_tl",
"UKSF_des_tl_l",
"UKSF_wdl_ar",
"UKSF_wdl_ar_l",
"UKSF_wdl_demo",
"UKSF_wdl_demo_l",
"UKSF_wdl_jtac",
"UKSF_wdl_jtac_l",
"UKSF_wdl_mrk",
"UKSF_wdl_mrk_l",
"UKSF_wdl_op",
"UKSF_wdl_op_l",
"UKSF_wdl_tl",
"UKSF_wdl_tl_l",
"US_Army_Soldier_AA",
"US_Army_Soldier_AR",
"US_Army_Soldier_AT",
"US_Army_Soldier_GL",
"US_Army_Soldier_HAT",
"US_Army_Soldier_LAT",
"US_Army_Soldier_MG",
"US_Army_Soldier_SL",
"US_Army_Soldier_TL",
"US_Army_Soldier2",
"US_Army_SoldierM_Marksman",
"US_Army_SoldierS",
"US_Army_SoldierS_Engineer",
"US_Army_SoldierS_SniperH",
"USSOF_US_Navy_SEALs_Antitank",
"USSOF_US_Navy_SEALs_Grenadier",
"USSOF_US_Navy_SEALs_Leader",
"USSOF_US_Navy_SEALs_Machinegunner",
"USSOF_US_Navy_SEALs_Marksman",
"USSOF_US_Navy_SEALs_Saboteur",
"USSOF_US_Navy_SEALs_Saboteur_SD",
"USSOF_US_Navy_SEALs_Sapper",
"USSR_solcheytac",
"USSR_solcheytac_sd",
"Winter_SOF_AC",
"Winter_SOF_AT",
"Winter_SOF_DA1",
"Winter_SOF_DA1a",
"Winter_SOF_DA1b",
"Winter_SOF_DA1c",
"Winter_SOF_GL",
"Winter_SOF_Marksman",
"Winter_SOF_MG",
"Winter_SOF_Sabot",
"Winter_SOF_TL"
];
};

AllPlayers = AllPlayers + CSCMenClothing + CSCWomanClothing; 

CHAMELEON_CLOTHING_LIST = [];
diag_log format ["Chameleon: Initializion Complete."];
